import { config } from "dotenv";
config();
export const PORT = process.env.PORT!;
export const MONGO_URI = process.env.MONGO_URI!;  
export const MONGO_DB = process.env.MONGO_DB!;
export const DB_HOST = process.env.DB_HOST!;
export const DB_USER = process.env.DB_USER!;
export const DB_PASS = process.env.DB_PASS!;
export const DB_NAME = process.env.DB_NAME!;
export const CRON_SCHEDULE= process.env.CRON_SCHEDULE!;
export const API_KEY= process.env.API_KEY!;
export const CAMPUS_ID_MF= process.env.CAMPUS_ID_MF!;
export const CAMPUS_ID_SC= process.env.CAMPUS_ID_SC!;
export const CAMPUS_ID_QZ= process.env.CAMPUS_ID_QZ!;
export const CAMPUS_ID_BV= process.env.CAMPUS_ID_BV!;
export const BASE_URL_API= process.env.BASE_URL_API!;
export const TIME_ZONE= process.env.TIME_ZONE!;